language: python
sudo: false
env:
    global: CONDA_DEPENDENCIES="numpy scipy matplotlib scikit-learn h5py pillow pytest pytest-cov coverage"
            PIP_DEPENDENCIES="pytest-sugar pytest-faulthandler joblib nibabel flake8 coveralls https://api.github.com/repos/mne-tools/mne-python/zipball/master"
            MNE_LOGGING_LEVEL="warning"
matrix:
    include:
        - env: PYTHON_VERSION=3.6
        - env: PYTHON_VERSION=3.7
before_install:
    - git clone https://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
install:
    - python -c "import mne; mne.sys_info()"
    - python -c 'import mne; mne.datasets.testing.data_path(verbose=True)'
script:
    - pytest mne_sandbox
    - make flake
after_success:
    - coveralls
